import type { CustomProviderInternalConfig, ProviderTemplateInternal } from "../types.js";

export function createOpenAICompatibleTemplate(baseUrl: string, apiKey: string): ProviderTemplateInternal {
  return {
    id: "openai-compatible",
    name: "OpenAI Compatible",
    description: "Generic OpenAI-compatible API template",
    provider: "custom",
    version: "1.0.0",
    author: "paracosm",
    defaultConfig: {
      providerId: "openai-compatible",
      name: "OpenAI Compatible",
      description: "Generic OpenAI-compatible API",
      baseUrl,
      authentication: {
        type: "bearer",
        headerName: "Authorization",
        tokenTemplate: apiKey,
      },
      requestMapping: {
        endpoint: `${baseUrl}/chat/completions`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        bodyTemplate: {
          model: "",
          messages: [],
          temperature: 0.7,
          max_tokens: 4096,
          stream: false,
        },
        messagePath: "messages",
        modelPath: "model",
        temperaturePath: "temperature",
        maxTokensPath: "max_tokens",
        streamPathParam: "stream",
        customPaths: {},
      },
      responseMapping: {
        contentPath: "choices.0.message.content",
        usagePath: "usage",
        promptTokensPath: "prompt_tokens",
        completionTokensPath: "completion_tokens",
        totalTokensPath: "total_tokens",
        finishReasonPath: "choices.0.finish_reason",
        functionCallPath: "choices.0.message.function_call",
        functionCallNamePath: "name",
        functionCallArgumentsPath: "arguments",
        errorPath: "error",
        errorMessagePath: "error.message",
        errorCodePath: "error.code",
        customPaths: {},
      },
      streamConfig: {
        enabled: true,
        streamEndpoint: null,
        streamFormat: "sse",
        chunkContentPath: "choices.0.delta.content",
        chunkFinishPath: "choices.0.finish_reason",
        chunkUsagePath: null,
        delimiter: "\n",
        heartbeatIntervalMs: 15000,
      },
      healthCheckEndpoint: "/models",
      rateLimitRpm: 500,
      timeoutMs: 30000,
    },
    capabilities: [
      { name: "chat", supported: true, details: {}, limitations: [] },
      { name: "streaming", supported: true, details: {}, limitations: [] },
      { name: "function_calling", supported: true, details: {}, limitations: ["Depends on provider"] },
      { name: "embeddings", supported: false, details: {}, limitations: ["Not all providers support this"] },
    ],
  };
}
